apiVersion: azure.crossplane.io/v1alpha3
kind: ResourceGroup
metadata:
 name: geeksessions-rg
spec:
 location: eastus2
---
apiVersion: storage.azure.crossplane.io/v1alpha3
kind: Account
metadata:
 name: geeksessionsstorageaccount
spec:
 resourceGroupName: geeksessions-rg
 storageAccountSpec:
   kind: Storage
   location: eastus2
   sku:
     name: Standard_LRS
 writeConnectionSecretToRef:
   namespace: default
   name: storageaccount-connection-secret