apiVersion: apps/v1
kind: Deployment
metadata:
  name: geeksessions
  labels:
    app: geeksessions
spec:
  selector:
    matchLabels:
      app: geeksessions
  template:
    metadata:
      labels:
        app: geeksessions
    spec:
      containers:
      - name: geeksessions
        image: bacfelix002/geeksessions
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: geeksessions
  labels:
    app: geeksessions
spec:
  minReplicas: 2
  maxReplicas: 6
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: geeksessions
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 25

