apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: geeksessions
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: geeksessions/app
    repoURL: https://github.com/zygabonda/combine-infra-services-apps
    targetRevision: HEAD
  destination:
    namespace: production
    server: https://35.185.12.140
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
